class PingHandler:
    def __init__(self, history_size: int = 10) -> None: ...
    def Terminate(self) -> None: ...
    def GetCurrentPing(self) -> int: ...
    def GetAveragePing(self) -> int: ...
    def GetMinPing(self) -> int: ...
    def GetMaxPing(self) -> int: ...
