from typing import Any, Callable, Sequence

# This module describes the recorded ImGui-style UI builder exposed by
# `Py4GW.UI` / `src/Py4GW_UI.cpp`.
# It is not the Guild Wars native frame/window creation layer.
# Helpers such as `draw_list_add_rect_filled` render through the overlay-backed
# recorder and should not be treated as native GW UI constructors.


class UI:
    def __init__(self) -> None: ...

    # State management
    def clear_ui(self) -> None: ...
    def clear_vars(self) -> None: ...
    def set_var(self, name: str, value: Any) -> None: ...
    def register_var(self, name: str, type: str, initial: Any = None) -> int: ...
    def is_finalized(self) -> bool: ...
    def layout_version(self) -> int: ...
    def recording_ignored_count(self) -> int: ...
    def perf_stats(self) -> dict[str, Any]: ...
    def vars(self, name: str) -> Any: ...
    def all_vars(self) -> dict[str, Any]: ...

    # UI recording (cached in C++, executed on render)
    def begin(self, name: str, p_open_var: str = "", flags: int = 0) -> "UI": ...
    def end(self) -> "UI": ...
    def text(self, value: str) -> "UI": ...
    def text_colored(self, value: str, color: tuple[float, float, float, float]) -> "UI": ...
    def text_wrapped(self, value: str) -> "UI": ...
    def bullet_text(self, value: str) -> "UI": ...
    def separator(self) -> "UI": ...
    def spacing(self) -> "UI": ...
    def same_line(self, offset_from_start_x: float = 0.0, spacing: float = -1.0) -> "UI": ...
    def button(self, label: str, clicked_var: str = "", width: float = 0.0, height: float = 0.0) -> "UI": ...
    def push_style_color(self, idx: int, color: tuple[float, float, float, float]) -> "UI": ...
    def pop_style_color(self, count: int = 1) -> "UI": ...
    def radio_button(self, label: str, var_name: str, button_index: int) -> "UI": ...
    def collapsing_header(self, label: str, open_var: str = "", flags: int = 0) -> "UI": ...
    def push_item_width(self, width: float) -> "UI": ...
    def pop_item_width(self) -> "UI": ...
    def set_next_window_size(self, width: float, height: float, cond: int = 0) -> "UI": ...
    def set_next_window_pos(self, x: float, y: float, cond: int = 0) -> "UI": ...
    def begin_tooltip(self) -> "UI": ...
    def end_tooltip(self) -> "UI": ...
    def text_disabled(self, value: str) -> "UI": ...
    def begin_disabled(self, disabled: bool = True) -> "UI": ...
    def end_disabled(self) -> "UI": ...
    def begin_group(self) -> "UI": ...
    def end_group(self) -> "UI": ...
    def indent(self, indent_w: float = 0.0) -> "UI": ...
    def unindent(self, indent_w: float = 0.0) -> "UI": ...
    def small_button(self, label: str, clicked_var: str = "") -> "UI": ...
    def menu_item(self, label: str, clicked_var: str = "") -> "UI": ...
    def open_popup(self, popup_id: str) -> "UI": ...
    def close_current_popup(self) -> "UI": ...
    def begin_table(self, table_id: str, columns: int, flags: int = 0) -> "UI": ...
    def end_table(self) -> "UI": ...
    def table_setup_column(self, label: str, flags: int = 0, init_width_or_weight: float = 0.0) -> "UI": ...
    def table_next_column(self) -> "UI": ...
    def table_next_row(self, row_flags: int = 0, min_row_height: float = 0.0) -> "UI": ...
    def table_set_column_index(self, column_n: int) -> "UI": ...
    def table_headers_row(self) -> "UI": ...
    def begin_child(self, child_id: str, width: float = 0.0, height: float = 0.0, border: bool = False, flags: int = 0) -> "UI": ...
    def end_child(self) -> "UI": ...
    def begin_tab_bar(self, str_id: str, flags: int = 0) -> "UI": ...
    def end_tab_bar(self) -> "UI": ...
    def begin_tab_item(self, label: str, flags: int = 0) -> "UI": ...
    def end_tab_item(self) -> "UI": ...
    def begin_with_close(self, name: str, p_open_var: str, flags: int = 0) -> "UI": ...
    def begin_popup(self, popup_id: str, flags: int = 0) -> "UI": ...
    def end_popup(self) -> "UI": ...
    def begin_popup_modal(self, name: str, p_open_var: str = "", flags: int = 0) -> "UI": ...
    def end_popup_modal(self) -> "UI": ...
    def begin_combo(self, label: str, preview_value: str, flags: int = 0) -> "UI": ...
    def end_combo(self) -> "UI": ...
    def selectable(self, label: str, var_name: str, flags: int = 0, width: float = 0.0, height: float = 0.0) -> "UI": ...
    def new_line(self) -> "UI": ...
    def invisible_button(self, label: str, width: float, height: float, clicked_var: str = "") -> "UI": ...
    def progress_bar(self, fraction: float, size_arg: float = -1.0, overlay: str = "") -> "UI": ...
    def progress_bar_ex(self, fraction: float, size_arg_x: float, size_arg_y: float, overlay: str = "") -> "UI": ...
    def dummy(self, width: float, height: float) -> "UI": ...
    def get_cursor_screen_pos(self, out_x_var: str, out_y_var: str) -> "UI": ...
    def set_cursor_screen_pos(self, x: float, y: float) -> "UI": ...
    def draw_list_add_line(self, x1: float, y1: float, x2: float, y2: float, col: int, thickness: float) -> "UI": ...
    def draw_list_add_rect(
        self,
        x1: float,
        y1: float,
        x2: float,
        y2: float,
        col: int,
        rounding: float = 0.0,
        rounding_corners_flags: int = 0,
        thickness: float = 1.0,
    ) -> "UI": ...
    def draw_list_add_rect_filled(
        self,
        x1: float,
        y1: float,
        x2: float,
        y2: float,
        col: int,
        rounding: float = 0.0,
        rounding_corners_flags: int = 0,
    ) -> "UI": ...
    def draw_list_add_text(self, x: float, y: float, col: int, text: str) -> "UI": ...
    def calc_text_size(self, text: str, out_x_var: str, out_y_var: str) -> "UI": ...
    def get_content_region_avail(self, out_x_var: str, out_y_var: str) -> "UI": ...
    def is_item_hovered(self, out_var: str) -> "UI": ...
    def set_clipboard_text(self, text: str) -> "UI": ...
    def get_clipboard_text(self, out_var: str) -> "UI": ...
    def color_edit4(self, label: str, var_name: str, flags: int = 0) -> "UI": ...
    def set_tooltip(self, text: str) -> "UI": ...
    def show_tooltip(self, text: str) -> "UI": ...
    def is_window_collapsed(self, out_var: str) -> "UI": ...
    def get_window_pos(self, out_x_var: str, out_y_var: str) -> "UI": ...
    def get_window_size(self, out_x_var: str, out_y_var: str) -> "UI": ...
    def checkbox(self, label: str, var_name: str) -> "UI": ...
    def checkbox_slot(self, label: str, slot: int) -> "UI": ...
    def input_text(self, label: str, var_name: str, flags: int = 0) -> "UI": ...
    def input_text_slot(self, label: str, slot: int, flags: int = 0) -> "UI": ...
    def input_int(self, label: str, var_name: str) -> "UI": ...
    def input_int_slot(self, label: str, slot: int) -> "UI": ...
    def input_float(self, label: str, var_name: str) -> "UI": ...
    def input_float_slot(self, label: str, slot: int) -> "UI": ...
    def slider_int(self, label: str, var_name: str, v_min: int, v_max: int) -> "UI": ...
    def slider_int_slot(self, label: str, slot: int, v_min: int, v_max: int) -> "UI": ...
    def slider_float(self, label: str, var_name: str, v_min: float, v_max: float) -> "UI": ...
    def slider_float_slot(self, label: str, slot: int, v_min: float, v_max: float) -> "UI": ...
    def combo(self, label: str, var_name: str, items: Sequence[str]) -> "UI": ...
    def combo_slot(self, label: str, slot: int, items: Sequence[str]) -> "UI": ...

    # Optional callback block support (if enabled in C++)
    def python_callable(self, fn: Callable[[dict[str, Any]], Any]) -> "UI": ...

    # Resolve variable names to slots once after recording
    def finalize(self) -> None: ...

    # Execute recorded UI for the current frame
    def render(self) -> None: ...


