"""
Quest Name and ID mappings for Guild Wars.
Provides convenient lookups by quest name or ID.
"""

QUEST_DATA = {
    0: "The Ascalon Settlement",
    1: "The Villainy of Galrath",
    2: "Bandit Trouble",
    3: "A Gift for Jalis Ironhammer",
    4: "To Kryta: Journey's End",
    5: "Graven Images",
    6: "The Hot Springs Murders",
    7: "The Last Hog",
    8: "The Lost Princess",
    9: "Duties of a Lionguard",
    10: "The Royal Papers",
    11: "A Journey of Redemption",
    12: "Blankets for the Settlers",
    13: "Orrian Excavation",
    14: "Malaquire's Test",
    15: "Reversing the Skales",
    16: "The Undead Hordes",
    17: "Lagaan's Ordeal",
    18: "Lagaan's Gratitude",
    19: "Report to the White Mantle",
    20: "Merchant's Plea",
    21: "A Belated Betrothal",
    22: "Ancient Secrets",
    23: "The Forgotten Ones",
    24: "Forgotten Wisdom",
    25: "Ghostly Vengeance",
    26: "Into the Unknown",
    27: "The Misplaced Sword",
    28: "Sands Of Souls",
    29: "The Mesmer's Path",
    30: "The Necromancer's Path",
    31: "The Elementalist's Path",
    32: "The Monk's Path",
    33: "The Warrior's Path",
    34: "The Ranger's Path",
    35: "War Preparations",
    36: "The Hunter's Horn",
    37: "The Supremacy of Air",
    38: "Rites of Remembrance",
    39: "Little Thom's Big Cloak",
    40: "The Vineyard Problem",
    41: "Bandit Raid",
    42: "A Test of Marksmanship",
    43: "The Power of Blood",
    44: "The Rogue's Replacement",
    45: "Charr in the Catacombs",
    46: "Charr at the Gate",
    47: "The Accursed Path",
    48: "The Poison Devourer",
    49: "Domination Magic (quest)",
    50: "The True King",
    51: "The Egg Hunter",
    52: "The Worm Problem",
    53: "The Prize Moa Bird",
    54: "Further Adventures",
    55: "The Wayward Wizard",
    56: "Adventure with an Ally",
    57: "The Orchard",
    58: "A Gift for Althea",
    59: "Gwen's Flute (quest)",
    60: "Warrior's Challenge",
    61: "Tithe for Ashford Abbey",
    62: "Unsettling Rumors",
    63: "A New Mesmer Trainer",
    64: "A New Necromancer Trainer",
    65: "A New Elementalist Trainer",
    66: "A New Monk Trainer",
    67: "A New Warrior Trainer",
    68: "A New Ranger Trainer",
    69: "Across the Wall",
    70: "Poor Tenant",
    71: "A Mesmer's Burden",
    72: "The Necromancer's Novice",
    73: "The Elementalist Experiment",
    74: "A Monk's Mission",
    75: "Grawl Invasion",
    76: "The Ranger's Companion",
    77: "Protection Prayers (quest)",
    78: "Opposition to the King",
    79: "A Second Profession",
    80: "Message from a Friend",
    81: "Mesmer Test",
    82: "Necromancer Test",
    83: "Elementalist Test",
    84: "Monk Test",
    85: "Warrior Test",
    86: "Ranger Test",
    87: "The Blessings of Balthazar",
    88: "Unnatural Growths",
    89: "The Path to Glory",
    90: "Trouble in the Woods",
    91: "White Mantle Wrath: A Helping Hand",
    92: "Urgent Warning",
    93: "Blood And Smoke",
    94: "Dropping Eaves",
    95: "A Brother's Fury",
    96: "Eye For Profit",
    97: "Mysterious Message (Prophecies quest)",
    98: "The Price of Steel",
    99: "White Mantle Wrath: Demagogue's Vanguard",
    100: "Passage Through The Dark River",
    101: "Clear the Chamber",
    102: "Servants of Grenth",
    103: "Unwanted Guests",
    104: "Demon Assassin",
    105: "Imprisoned Spirits",
    106: "The Four Horsemen",
    107: "Terrorweb Queen",
    108: "Escort of Souls",
    109: "Restoring Grenth's Monuments",
    110: "Wrathful Spirits",
    111: "Charr Reinforcements",
    112: "Symon's History of Ascalon",
    113: "Experimental Elixir",
    114: "Trying Times",
    115: "Unnatural Creatures",
    116: "The Charr Patrol",
    117: "The Charr Staging Area",
    118: "A Cure for Ralena",
    119: "Casualty Report",
    120: "Death in the Ruins",
    121: "Fallen Soldiers",
    122: "Oberan's Rage",
    123: "Althea's Ashes",
    124: "Hammer and Anvil",
    125: "The Geomancer's Test",
    126: "The Way of the Geomancer",
    127: "Shalev's Task",
    128: "Elemental Knowledge",
    129: "The Duke's Daughter",
    130: "Barradin's Advance",
    131: "Fires in the East",
    132: "Fires in the North",
    133: "Frontier Gate Fugitives",
    134: "Bounty for Chieftain Murg",
    135: "Helping the People of Ascalon",
    136: "Cities of Ascalon",
    137: "Counting the Fallen",
    138: "Scavengers in Old Ascalon",
    139: "Garfazz Bloodfang (quest)",
    140: "The King's Message",
    141: "In Memory of Paulus",
    142: "Protecting Ascalon",
    143: "The Lost Master",
    144: "The Ambassador's Quandary",
    145: "Rastin's Ritual",
    146: "A Mission of Peace",
    147: "The Troublesome Artifact",
    148: "Barradin's Stand",
    149: "Army Life",
    150: "Into the Breach",
    151: "Military Matters",
    152: "The Red-Cloaked Deserter",
    153: "The Siege of Piken Square",
    154: "Replacement Healers",
    155: "Rogenn's Duel",
    156: "Regent Valley Defense",
    157: "Mesmerizing the Enemy",
    158: "The Stolen Artifact",
    159: "Scorched Earth (Prophecies quest)",
    160: "Sowing Seeds",
    161: "Gargoyle Trouble",
    162: "Endangered Species",
    163: "The Missing Melandru Relic",
    164: "Supplies for the Duke",
    165: "Ruins of Surmia (quest)",
    166: "Vanguard Equipment",
    167: "Deliver a Message to My Wife",
    168: "Recruits for Hollis",
    169: "The Krytan Ambassador",
    170: "Collect Charr Armor Set",
    171: "Defend the Wall",
    172: "Slay Rotscale",
    173: "Slay Stank Reekfoul",
    174: "Repel Charr",
    175: "Scout Charr",
    176: "Collect Gargoyle Fangs",
    177: "Defend Droknar's Forge",
    178: "The Road to Borlis Pass",
    179: "To Kryta: The Ice Cave",
    180: "The Stone Summit Champion",
    181: "Renegade Necromancer",
    182: "The Deserters",
    183: "A Heart of Ice",
    184: "The Missing Artisan",
    185: "Helping the Dwarves",
    186: "Hungry Devourer",
    187: "Oswalt's Epitaph",
    188: "Securing the Vale",
    189: "Minaar's Trouble",
    190: "Iron Horse War Machine",
    191: "Minaar's Worry",
    192: "Stone Summit Beastmasters",
    193: "Slay Frostbite",
    194: "The Hero's Journey",
    195: "The Hero's Challenge",
    196: "Seeking The Seer",
    197: "Shiverpeak Stragglers",
    198: "The Way is Blocked",
    199: "To Kryta: Refugees",
    200: "The Wayward Monk",
    201: "Into the Breach",
    202: "Defend the Temple of War",
    203: "Army of Darkness",
    204: "The Wailing Lord",
    205: "A Gift of Griffons",
    206: "Slaves of Menzies",
    207: "Restore the Temple of War",
    208: "The Hunt",
    209: "The Eternal Forgemaster",
    210: "Champions of Orr",
    211: "Tower of Strength",
    212: "Tower of Courage",
    213: "Final Blow",
    214: "Wisdom of the Druids",
    215: "Family Ties (Prophecies quest)",
    216: "The Weaver of Nebo",
    217: "War Preparations",
    218: "War Preparations",
    219: "War Preparations",
    220: "War Preparations",
    221: "War Preparations",
    222: "War Preparations",
    223: "The False Gods",
    224: "Khobay the Betrayer",
    225: "Caravan in Trouble",
    226: "Defend North Kryta Province",
    227: "Defend Denravi",
    228: "The Last Day Dawns",
    229: "The Titan Source",
    230: "Cold One",
    231: "The Forge Heart",
    232: "Wrenches In The Gears",
    233: "Unspeakable, Unknowable",
    234: "To Sorrow's Furnace",
    235: "Noble Intentions",
    236: "Noble Intentions Plan B",
    237: "Kilroy Stonekin (quest)",
    238: "Summit Slaves",
    239: "Gathering Resources",
    240: "Unruly Slaves",
    241: "Fire in the Hole",
    242: "Tasca's Reprise",
    243: "Subversive Ideas",
    244: "Political Ramifications",
    245: "The Final Assault",
    246: "Seek Out Headmaster Lee",
    247: "Seek Out Headmaster Kaa",
    248: "Seek Out Headmaster Kuju",
    249: "Seek Out Headmaster Vhang",
    250: "Seek Out Headmaster Zhan",
    251: "Seek Out Headmaster Amara",
    252: "Seek Out Headmaster Greico",
    253: "Seek Out Headmaster Quin",
    254: "Locate Jinzo",
    255: "Locate Mei Ling",
    256: "Locate Reng Ku",
    257: "Locate Ronsu",
    258: "Locate Sister Tai",
    259: "Locate Talon Silverwing",
    260: "Locate Sujun",
    261: "Locate Professor Gai",
    262: "Track Down Panaku",
    263: "Track Down Lo Sha",
    264: "Track Down Su",
    265: "Track Down Kai Ying",
    266: "Track Down Brother Pe Wan",
    267: "Track Down Weng Gha",
    268: "Track Down Zho",
    269: "Track Down Ang the Ephemeral",
    270: "Opening Strike",
    271: "Cleansing the Shrine",
    272: "Little Creatures",
    273: "Spark of Interest",
    274: "Stale Mate",
    275: "Talon's Duel",
    276: "Free the Fur",
    277: "Minions Gone Wild",
    278: "Dual Strike",
    279: "Lo Sha's Gift",
    280: "Reaping the Naga",
    281: "Sparring Elements",
    282: "Seeking a Cure",
    283: "The Crop Thieves",
    284: "The Yeti Hunt",
    285: "Shacked Spirits",
    286: "An Audience with Master Togo (assassin)",
    287: "An Audience with Master Togo (mesmer)",
    288: "An Audience with Master Togo (necromancer)",
    289: "An Audience with Master Togo (elementalist)",
    290: "An Audience with Master Togo (monk)",
    291: "An Audience with Master Togo (warrior)",
    292: "An Audience with Master Togo (ranger)",
    293: "An Audience with Master Togo (ritualist)",
    294: "Speak with Headmaster Lee (Assassin)",
    295: "Speak with Headmaster Kaa (Mesmer)",
    296: "Speak with Headmaster Kuju (Necromancer)",
    297: "Speak with Headmaster Vhang (Elementalist)",
    298: "Speak with Headmaster Amara (Monk)",
    299: "Speak with Headmaster Zhan (Warrior)",
    300: "Speak with Headmaster Greico (Ranger)",
    301: "Speak with Headmaster Quin (Ritualist)",
    302: "Defense Against Hexes",
    303: "Disruption",
    304: "Skill Chaining",
    305: "Snaring Course",
    306: "Disenchantment Course",
    307: "Condition Removal",
    308: "Advanced Defense Techniques",
    309: "Elementalist Insignia",
    310: "Warrior Insignia",
    311: "Mesmer Insignia",
    312: "Monk Insignia",
    313: "Necromancer Insignia",
    314: "Ranger Insignia",
    315: "Ritualist Insignia",
    316: "Assassin Insignia",
    317: "Choose Your Secondary Profession (Factions quest)",
    318: "A Formal Introduction",
    319: "The Sickened Village",
    320: "The Red Frog",
    321: "The Kaguchi Brothers",
    322: "The Box of Illusions",
    323: "Old Friends, Dark Times",
    324: "Power Surge",
    325: "Cleansing the Steel",
    326: "The Stone of the Elements",
    327: "Assassination Attempt",
    328: "Little Lost Bear",
    329: "Imperial Assistance",
    330: "Medical Emergency",
    331: "Red Tape",
    332: "Assist the Guards",
    333: "Straight to the Top",
    334: "Drink from the Chalice of Corruption",
    335: "Refuse to Drink",
    336: "The Search for a Cure",
    337: "Seek out Brother Tosai",
    338: "An End to Suffering",
    339: "Warning the Tengu",
    340: "The Threat Grows",
    341: "Journey to the Master",
    342: "The Road Less Traveled",
    343: "Looking For Trouble",
    344: "To the Rescue (Factions quest)",
    345: "To Zen Daijun",
    346: "Lost Treasure",
    347: "Mantid Hatchlings",
    348: "An Unwelcome Guest",
    349: "A Master's Burden",
    350: "To Tahnnakai Temple",
    351: "Into the Whirlpool",
    352: "Journey to House zu Heltzer",
    353: "Journey to Cavalon",
    354: "Naga Oil",
    355: "Street Justice",
    356: "Finding The Oracle",
    357: "Closer to the Stars",
    358: "Appearance of the Naga",
    359: "The Rite of Valor",
    360: "Death with Honor",
    361: "The Nameless Masters",
    362: "The Path of the Zaishen Elite",
    363: "The Team Trials",
    364: "Kurzick Supply Lines",
    365: "Scouting Ferndale",
    366: "Scout the Coast",
    367: "Securing Echovald Forest",
    368: "Duel of the Houses",
    369: "The Jade Arena",
    370: "In the Army (Luxon)",
    371: "Scouting Maishang Hills",
    372: "Luxon Supply Lines",
    373: "In the Army Now (Kurzick)",
    374: "Befriending the Kurzicks",
    375: "Befriending the Luxons",
    376: "Mayhem in the Market",
    377: "Welcome to Cantha",
    378: "The Defenders of the Forest",
    379: "A Meeting With the Emperor",
    380: "The Count's Daughter",
    381: "Stolen Eggs",
    382: "The Convocation",
    383: "Journey to the Whirlpool",
    384: "Taking Back the Palace",
    385: "Quimang's Last Stand",
    386: "The Siege at Tsumei Village",
    387: "Togo's Ultimatum",
    388: "Revenge of the Yeti",
    389: "The Agriculturist",
    390: "The Captured Son",
    391: "The Naga Source",
    392: "Sentimental Treasures",
    393: "Skin the Snake",
    394: "Pest Control",
    395: "The Thieving Nanny",
    396: "City Under Attack",
    397: "Battle in the Sewers",
    398: "The Ancient Forest",
    399: "Wicked Wardens",
    400: "Song and Stone",
    401: "A New Escort",
    402: "The Experimental Weaponsmith",
    403: "Melodic Gaki Flute",
    404: "Discord Wallow Lyre",
    405: "Rhythm Drinker Drum",
    406: "Envoy of the Dredge",
    407: "Temple of the Dredge",
    408: "Revolt of the Dredge",
    409: "The Halcyon Job",
    410: "Attack the Kurzicks!",
    411: "Protect the Halcyon",
    412: "Outcasts in the Quarry",
    413: "Challenge of Strength",
    414: "Artistic Endeavors",
    415: "The Beak of Darkness",
    416: "Wardens On the March",
    417: "Invoking the Saints",
    418: "If It Weren't for Bad Luck....",
    419: "Night Raiders",
    420: "Message on a Dragon Scale",
    421: "Messages, Messages Everywhere",
    422: "The Zenos Squad",
    423: "The Impossible Sea Monster",
    424: "Minister's Test",
    425: "Capturing the Orrian Tome",
    426: "A Tasty Morsel",
    427: "Wayward Guide",
    428: "A New Guide",
    429: "Getting Even",
    430: "Sticks and Stones",
    431: "Forgotten Retribution",
    432: "Defend Fort Aspenwood",
    433: "The Jade Quarry (Kurzick quest)",
    434: "Fort Aspenwood (quest)",
    435: "The Jade Quarry (Luxon quest)",
    436: "Mhenlo's Request",
    437: "The Bog Beast of Bokku",
    438: "A Belt Pouch",
    439: "Cash Crops",
    440: "Forming a Party",
    441: "Study Buddy",
    442: "The Dragon Hunter",
    443: "More Cowbell",
    444: "A Letter Home",
    445: "Return of the Yeti",
    446: "The Challenge",
    447: "Captured",
    448: "The Emperor in Peril",
    449: "The Plot Thickens",
    450: "It Ends Here",
    451: "Masters of Corruption",
    452: "The Drunken Master",
    453: "Eliminate the Am Fah",
    454: "Eliminate the Jade Brotherhood",
    455: "Problem Salving",
    456: "Going Home",
    457: "Missing Daughter",
    458: "Too High a Price",
    459: "The Xunlai Agent",
    460: "Luxury Goods",
    461: "Charting the Forests",
    462: "Charting the Jade Sea",
    463: "Stemming the Tide",
    464: "The Missing Corpses",
    465: "The Missing Link",
    466: "The Afflicted Guard",
    467: "Seeking Shelter",
    468: "Housing for Refugees",
    469: "A Monstrous Revelation",
    470: "The Shadow Blades",
    471: "Lambs to the Slaughter",
    472: "Sea of Green, Canopy of Stone",
    473: "Feed the Hungry",
    474: "Passing the Buck",
    475: "Raze the Roost",
    476: "Last of the Breed",
    477: "Refuse the King",
    478: "The Growing Threat",
    479: "Chaos in Kryta",
    480: "Vanishing Spirits",
    481: "Pilgrimage",
    482: "Requiem for a Brain",
    483: "Under New Management",
    484: "Destroy the Ungrateful Slaves",
    485: "A Show of Force",
    486: "Temple of the Monoliths",
    487: "Return of the Undead King",
    488: "Strange Bedfellows",
    489: "She Hungers",
    490: "The Council is Called",
    491: "Desperate Measures",
    492: "The Search for survivors",
    493: "A Sound of Ancient Horns",
    494: "Garden Chores",
    495: "Which Way Did He Go?",
    496: "One Man's Dream",
    497: "Puzzling Parchment",
    498: "A Brief Introduction",
    499: "Plague of Frogs",
    500: "Between a Rock...",
    501: "Botanical Research",
    502: "Rally The Princes",
    503: "All's Well That Ends Well",
    504: "Warning Kehanni",
    505: "Calling the Order",
    506: "Greed and Regret",
    507: "Pledge of the Merchant Princes",
    508: "An Old Man's Past",
    509: "An Old Man's Shame",
    510: "To the Rescue (Nightfall quest)",
    511: "Coffer of Joko",
    512: "Data Mining",
    513: "The Madness of Prophecy",
    514: "Protect the Learned",
    515: "Reclaiming the Temple",
    516: "The Search for Enlightenment",
    517: "Summertime for Bokka",
    518: "In Defense of Theatre",
    519: "Worst. Performance. Ever.",
    520: "The Show Must Go On",
    521: "Valley of the Rifts",
    522: "Population Control",
    523: "Destroy the Harpies",
    524: "Guard Rescue",
    525: "Gift of the Djinn",
    526: "Interception",
    527: "Old Friends",
    528: "For Your Ears Only",
    529: "The Scourge of Vabbi",
    530: "The Hanging Gardener",
    531: "Scorched Earth (Nightfall quest)",
    532: "Extinction",
    533: "Insatiable Appetite",
    534: "Building the Base: Prisoners of War",
    535: "Building the Base: The Interrogation",
    536: "Building the Base: The Meeting",
    537: "The Tools of War",
    538: "Feeding Frenzy",
    539: "You Can Run...",
    540: "Centaur Concerns",
    541: "Mirza's Last Stand",
    542: "Battle of Turai's Procession",
    543: "A Question of Morality",
    544: "A Bushel of Trouble",
    545: "The Great Zehtuka (quest)",
    546: "Eavesdropping",
    547: "A Little Recon",
    548: "Hunted!",
    549: "The Great Escape",
    550: "And a Hero Shall Lead Them",
    551: "To Vabbi!",
    552: "Centaur Blackmail",
    553: "Mysterious Message (Nightfall quest)",
    554: "Secrets in the Shadow",
    555: "To Kill a Demon",
    556: "For a Price",
    557: "No Me, No Kormir",
    558: "A Thorn in Varesh's Side",
    559: "Tendering an Offer",
    560: "Estate Planning",
    561: "Family Ties (Nightfall quest)",
    562: "A Message for Janeera",
    563: "Strange Allies",
    564: "The Foolhardy Father",
    565: "The Young Lady Vanishes",
    566: "Old Woman River",
    567: "A Fool's Luck",
    568: "Herds to the Slaughter",
    569: "Koss's Elixir",
    570: "Drake in a Cage",
    571: "Troubled Lands",
    572: "Ancestral Anguish",
    573: "Total Corruption",
    574: "Fish in a Barrel",
    575: "Melonni's Meditations",
    576: "Weird Waters",
    577: "A Prescription for Conscription",
    578: "Undead Defenders",
    579: "The Cold Touch of the Past",
    580: "Raising an Army",
    581: "Heart or Mind: Garden in Danger",
    582: "The Hallowed Point",
    583: "A Deal's a Deal",
    584: "Horde of Darkness",
    585: "Family Soul",
    586: "Heart or Mind: Ronjok in Danger",
    587: "Assault on Beknur Harbor",
    588: "Moa'vu'Kaal, Awakened",
    589: "The Cyclone Palace",
    590: "Down on the Bayou",
    591: "Double Dog Dare",
    592: "A Message Home",
    593: "One Good Turn Deserves Another",
    594: "What Do You Do with a Drunken Shauben?",
    595: "Secret Passage",
    596: "Choose Your Secondary Profession (Nightfall quest)",
    597: "Corsair Vengeance",
    598: "Defender's Choice",
    599: "The Lone Raider",
    600: "Primary Training",
    601: "Secondary Training",
    602: "A Hidden Threat",
    603: "Wandered Off Again",
    604: "Anger of the Stone Face",
    605: "The Cult of the Stone Face",
    606: "Stone-Faced Orders",
    607: "Armored Transport",
    608: "Quality Steel",
    609: "Material Girl",
    610: "Suwash the Pirate",
    611: "Catch of the Day",
    612: "Flamingo-ing... going... gone.",
    613: "A Leap of Faith",
    614: "Zaishen Elite (quest)",
    615: "Student Jin",
    616: "Student Sousuke",
    617: "Feast of Bokka",
    618: "A Ghostly Request",
    619: "Ghosts in the Graveyard",
    620: "Skree Hatchling Season",
    621: "A Friend in Need",
    622: "A Father's Fate",
    623: "Second Born",
    624: "First Born",
    625: "Third Born",
    626: "Identity Theft",
    627: "Need More Stuff",
    628: "To Dye For",
    629: "Missing Shipment",
    630: "Blow Out Sale!",
    631: "Scholarly Affairs",
    632: "Leaving a Legacy",
    633: "The Honorable General",
    634: "Signs and Portents",
    635: "Isle of the Dead (quest)",
    636: "Bad Tide Rising",
    637: "Special Delivery",
    638: "Big News, Small Package",
    639: "Following the Trail",
    640: "The Iron Truth",
    641: "Trial by Fire",
    642: "War Preparations (Recruit Training)",
    643: "War Preparations (Wind and Water)",
    644: "War Preparations (Ghost Reconnaissance)",
    645: "The Time is Nigh",
    646: "A Loose Cannon",
    647: "Diamond in the Rough",
    648: "Map-Travel Inventor",
    649: "Honing your Skills",
    650: "Voices in the Night",
    651: "Corsair Invasion",
    652: "A Peaceful Solution",
    653: "Hog Hunt",
    654: "A Delayed Delivery",
    655: "A Troubling Theory",
    656: "A Mysterious Missive",
    657: "A Perplexing Plague",
    658: "A Stolen Spore",
    659: "Proof of Courage",
    660: "Quarry Quandry",
    661: "Queen of the Quarry",
    662: "A Sticky Operation",
    663: "Rising Suns",
    664: "Re-enlist Rojis",
    665: "Skale and Magic Compass",
    666: "To See the Sights",
    667: "To Ask For More",
    668: "Money on the Side",
    669: "Fury of a Grieving Heart",
    670: "Crypt-ology",
    671: "Stolen Supplies",
    672: "Loyal 'til the End",
    673: "A Personal Vault",
    674: "Trade Relations",
    675: "Rally the Recruits (Tutorial)",
    676: "Into Chahbek Village",
    677: "Take the Shortcut (Skip Tutorial)",
    678: "A Decayed Monument",
    679: "Goren's Stuff: Part 1",
    680: "Attack at the Kodash",
    681: "Crossing the Desolation (Zerai the Learner)",
    682: "Melonni Goes Recruiting",
    683: "Securing Champion's Dawn",
    684: "Crossing the Desolation (Lonai)",
    685: "The Apostate",
    686: "Breaking the Broken",
    687: "A Flickering Flame",
    688: "Dismember the Titans",
    689: "Cover Your Tracks",
    690: "Dark Gateway",
    691: "They Only Come Out at Night",
    692: "Invasion From Within",
    693: "Drink of the Gods",
    694: "The Troubled Keeper",
    695: "Open Season",
    696: "Good Demon Hunting",
    697: "Holding the Line",
    698: "A Fleshy Operation",
    699: "Bad Fortune",
    700: "Know Thine Enemy",
    701: "Uncharted Territory",
    702: "Kormir's Crusade",
    703: "All Alone in the Darkness",
    704: "Passing the Luck",
    705: "Blueprint of the Fall",
    706: "Escape from the Torment",
    707: "Faded Memory",
    708: "A History of Violence",
    709: "Quiz the Recruits",
    710: "Koss Goes Recruiting",
    711: "Never Fight Alone",
    712: "Command Training",
    713: "Goren's Stuff: Part 2",
    714: "The Toy's Story",
    715: "Rising in the Ranks: Master Sergeant",
    716: "Rising in the Ranks: First Spear",
    717: "Misela, the Middle Child",
    718: "Mutu, the Oldest Child",
    719: "Jedur, the Youngest Child",
    720: "Norgu's Nightfall",
    721: "The Role of a Lifetime",
    722: "Brains or Brawn",
    723: "Sunspears in Kryta",
    724: "Sunspears in Cantha",
    725: "Terror in Tyria",
    726: "Plague in Cantha",
    727: "The Command Post",
    728: "The Dejarin Estate",
    729: "Gain Norgu",
    730: "Gain Goren",
    731: "Gain Margrid",
    732: "Gain Master of Whispers",
    733: "Gain Jin",
    734: "Gain Sousuke",
    735: "Gain Olias",
    736: "Gain Zenmai",
    737: "Battle Preparations",
    738: "The Time is Nigh",
    739: "Drakes on the Plain",
    740: "Capturing the Signet of Capture",
    741: "A Land of Heroes",
    742: "Breaching the Stygian Veil",
    743: "Foundry Breakout",
    744: "The Foundry of Failed Creations (quest)",
    745: "The Oddbodies (quest)",
    746: "The Last Patrol",
    747: "The Missing Patrol",
    748: "Into the Fire",
    749: "Deathbringer Company",
    750: "Finding a Purpose",
    751: "The City of Torc'qua",
    752: "The Rifts Between Us",
    753: "To the Rescue!",
    754: "Mallyx the Unyielding (quest)",
    755: "Brood Wars",
    756: "How the Grentches Stole Wintersday",
    757: "Spreading the Wintersday Spirit",
    758: "White Mist",
    759: "The Gift of Giving",
    760: "Save the Reindeer",
    761: "Find the Stolen Presents",
    762: "A Very Grentchie Wintersday",
    763: "The Greatest Snowman Ever Made",
    764: "You're a Mean One, Mr. Grenth",
    765: "In Grenth's Defense",
    766: "Army Wife",
    767: "Impressing the Girl",
    768: "Tossing the Bouquet",
    769: "Making Friends",
    770: "Missing Suitor",
    771: "Avad on the Run",
    772: "The Eternal Debate",
    773: "The Contest",
    774: "Consolation",
    775: "A Burning Desire",
    776: "The Big Bang",
    777: "Douse Your Enthusiasm",
    778: "Hopeless Romantic",
    779: "Fire in the Sky",
    780: "The Knights Who Say Nian",
    781: "Just My Luck",
    782: "All for One and One for Justice",
    783: "Chasing Zenmai",
    784: "Out of Kourna",
    785: "Counting the Fallen",
    786: "Commissioning a Memorial",
    787: "Ancient History",
    788: "Finding a Purpose",
    789: "Money Back Guarantee",
    790: "Against the Charr",
    791: "Warband of Brothers",
    792: "Search for the Ebon Vanguard",
    793: "The Missing Vanguard",
    794: "Scrambled Reinforcements",
    795: "The Rampaging Yetis",
    796: "The Shrine of Maat",
    797: "A Strange Request",
    798: "Darkness at Kaitan",
    799: None,
    800: "Flames of the Bear Spirit",
    801: "Temple of the Damned",
    802: "Giriff's War",
    803: "Veiled Threat",
    804: "Lost Souls",
    805: "Kathandrax's Crusher",
    806: "Curse of the Nornbear",
    807: "The Elusive Golemancer",
    808: "Tracking the Nornbear",
    809: "The Anvil of Dragrimmar",
    810: "Cold Vengeance",
    811: "The Misanthropic Jotun Principle",
    812: "Lab Space",
    813: "A Gate Too Far",
    814: "Vision of the Raven Spirit",
    815: "Genius Operated Living Enchanted Manifestation",
    816: "Destruction's Depths",
    817: "Heart of the Shiverpeaks (quest)",
    818: "Finding the Bloodstone",
    819: "Finding Gadd",
    820: "A Little Help",
    821: "I Feel the Earth Move Under Cantha's Feet",
    822: "Hole of Istan",
    823: "What Lies Beneath",
    824: "The Beginning of the End",
    825: "Tekks's War",
    826: "Worthy Deeds (Done Dirt Cheap)",
    827: "Little Workshop of Horrors",
    828: "Dredging the Depths",
    829: "Watch it Jiggle",
    830: "Anything You Can Do",
    831: "Krak's Cavalry",
    832: "Crystal Method",
    833: "The Blade's Essence",
    834: "The Arrow's Point",
    835: "Defending the Breach",
    836: "Cold as Ice",
    837: "In the Service of Revenge",
    838: "Truthseeker",
    839: "A Hunter's Pride",
    840: "Shadows in the Night",
    841: "Leader of the Pack",
    842: "Round 1: Fight!",
    843: "Round 2: Fight!",
    844: "Round 3: Fight!",
    845: "Round 4: Fight!",
    846: "Round 5: Fight!",
    847: "Final Round: Fight!",
    848: "Hero Tutorial",
    849: "Bear Club for Women",
    850: "The Great Norn Alemoot",
    851: "The Great Norn Alemoot",
    852: "Prenuptial Disagreement (female)",
    853: "Prenuptial Disagreement (male)",
    854: "Charr Invaders",
    855: "Bear Club for Men",
    856: "Kilroy Stonekin's Punch-Out Extravaganza!",
    857: "The Throwdown in a Norn Town",
    858: "Punch the Clown",
    859: "Destructive Research",
    860: "The Destroyer Challenge",
    861: "Falling Out",
    862: "Forgotten Relics",
    863: None,
    864: "The Smell of Titan in the Morning",
    865: "Be Very, Very Quiet...",
    866: "Plan A",
    867: "Final Round, Championship Edition: Fight!",
    868: "Mano a Norn-o",
    869: "A Time for Heroes",
    870: "The Assassin's Revenge",
    871: "The Imploding Past",
    872: "Failure to Communicate",
    873: "Service: In Defense of the Eye",
    874: "Service: Practice, Dummy",
    875: "Polymock: Defeat Plurgg",
    876: "Polymock: Defeat Fonk",
    877: "Polymock: Defeat Dune Teardrinker",
    878: "Polymock: Defeat Grulhammer Silverfist",
    879: "Polymock: Defeat Necromancer Volumandus",
    880: "Polymock: Defeat Master Hoff",
    881: "Polymock: Defeat Blarp",
    882: "Polymock: Defeat Yulma",
    883: "Single Ugly Grawl Seeks Same for Mindless Destruction in Ascalon",
    884: "The Hunting of the Charr",
    885: "Frogstomp",
    886: "Give Peace a Chance",
    887: "The Cipher of Balthazar",
    888: "The Cipher of Dwayna",
    889: "The Cipher of Grenth",
    890: "The Cipher of Kormir",
    891: "The Cipher of Lyssa",
    892: "The Cipher of Melandru",
    893: "The Path to Revelations",
    894: "The Big Unfriendly Jotun",
    895: "Forbidden Fruit",
    896: None,
    897: "O Brave New World",
    898: "Lost Treasure of King Hundar",
    899: "Deeprunner's Map",
    900: "Attack on Jalis's Camp",
    901: "The Asura Trap",
    902: "Moths to a Flame",
    903: "Insidious Remnants",
    904: "Turning the Page",
    905: "Northern Allies",
    906: "Assault on the Stronghold",
    907: "Blood Washes Blood",
    908: "The Dawn of Rebellion",
    909: "What Must Be Done",
    910: "Nornhood",
    911: "The Justiciar's End",
    912: "Haunted",
    913: "Against the Destroyers",
    914: "Fire and Pain",
    915: "The Knowledgeable Asura",
    916: "Then and Now, Here and There",
    917: "The Last Hierophant",
    918: "Kilroy's Punchout Tournament",
    919: "Special Ops: Dragon's Gullet",
    920: "Special Ops: Flame Temple Corridor",
    921: "Special Ops: Grendich Courthouse",
    922: "The Tengu Accords",
    923: "The Battle of Jahai",
    924: "The Flight North",
    925: "The Rise of the White Mantle",
    926: "Straight to the Heart",
    927: "The Strength of Snow",
    928: "Deactivating P.O.X.",
    929: "Deactivating N.O.X.",
    930: "Deactivating R.O.X.",
    931: "Zinn's Task",
    932: "The Three Wise Norn",
    933: "Charr-broiled Plans",
    934: "Snowball Dominance",
    935: "Wintersday Cheer",
    936: "The Great Northern Wall (Zaishen quest)",
    937: "Fort Ranik (Zaishen quest)",
    938: "Ruins of Surmia (Zaishen quest)",
    939: "Nolani Academy (Zaishen quest)",
    940: "Borlis Pass (Zaishen quest)",
    941: "The Frost Gate (Zaishen quest)",
    942: "Gates of Kryta (Zaishen quest)",
    943: "D'Alessio Seaboard (Zaishen quest)",
    944: "Divinity Coast (Zaishen quest)",
    945: "The Wilds (Zaishen quest)",
    946: "Bloodstone Fen (Zaishen quest)",
    947: "Aurora Glade (Zaishen quest)",
    948: "Riverside Province (Zaishen quest)",
    949: "Sanctum Cay (Zaishen quest)",
    950: "Dunes of Despair (Zaishen quest)",
    951: "Thirsty River (Zaishen quest)",
    952: "Elona Reach (Zaishen quest)",
    953: "Augury Rock (Zaishen quest)",
    954: "The Dragon's Lair (Zaishen quest)",
    955: "Ice Caves of Sorrow (Zaishen quest)",
    956: "Iron Mines of Moladune (Zaishen quest)",
    957: "Thunderhead Keep (Zaishen quest)",
    958: "Ring of Fire (Zaishen quest)",
    959: "Abaddon's Mouth (Zaishen quest)",
    960: "Hell's Precipice (Zaishen quest)",
    961: "Zen Daijun (Zaishen quest)",
    962: "Vizunah Square (Zaishen quest)",
    963: "Nahpui Quarter (Zaishen quest)",
    964: "Tahnnakai Temple (Zaishen quest)",
    965: "Arborstone (Zaishen quest)",
    966: "Boreas Seabed (Zaishen quest)",
    967: "Sunjiang District (Zaishen quest)",
    968: "The Eternal Grove (Zaishen quest)",
    969: "Unwaking Waters (Zaishen quest)",
    970: "Gyala Hatchery (Zaishen quest)",
    971: "Raisu Palace (Zaishen quest)",
    972: "Imperial Sanctum (Zaishen quest)",
    973: None,
    974: None,
    975: None,
    976: None,
    977: None,
    978: "Chahbek Village (Zaishen quest)",
    979: "Jokanur Diggings (Zaishen quest)",
    980: "Blacktide Den (Zaishen quest)",
    981: "Consulate Docks (Zaishen quest)",
    982: "Venta Cemetery (Zaishen quest)",
    983: "Kodonur Crossroads (Zaishen quest)",
    984: "Rilohn Refuge (Zaishen quest)",
    985: "Moddok Crevice (Zaishen quest)",
    986: "Tihark Orchard (Zaishen quest)",
    987: "Dzagonur Bastion (Zaishen quest)",
    988: "Dasha Vestibule (Zaishen quest)",
    989: "Grand Court of Sebelkeh (Zaishen quest)",
    990: "Jennur's Horde (Zaishen quest)",
    991: "Nundu Bay (Zaishen quest)",
    992: "Gate of Desolation (Zaishen quest)",
    993: "Ruins of Morah (Zaishen quest)",
    994: "Gate of Pain (Zaishen quest)",
    995: "Gate of Madness (Zaishen quest)",
    996: "Abaddon's Gate (Zaishen quest)",
    997: None,
    998: None,
    999: None,
    1000: "Finding the Bloodstone (Zaishen quest)",
    1001: "The Elusive Golemancer (Zaishen quest)",
    1002: "G.O.L.E.M. (Zaishen quest)",
    1003: "Against the Charr (Zaishen quest)",
    1004: "Warband of Brothers (Zaishen quest)",
    1005: "Assault on the Stronghold (Zaishen quest)",
    1006: "Curse of the Nornbear (Zaishen quest)",
    1007: "Blood Washes Blood (Zaishen quest)",
    1008: "A Gate Too Far (Zaishen quest)",
    1009: "Destruction's Depths (Zaishen quest)",
    1010: "A Time for Heroes (Zaishen quest)",
    1011: None,
    1012: None,
    1013: None,
    1014: None,
    1015: None,
    1016: "Verata (Zaishen quest)",
    1017: "Rotscale (Zaishen quest)",
    1018: None,
    1019: "The Iron Forgeman (Zaishen quest)",
    1020: "The Darknesses (Zaishen quest)",
    1021: "Kepkhet Marrowfeast (Zaishen quest)",
    1022: "Harn and Maxine Coldstone (Zaishen quest)",
    1023: None,
    1024: "Kanaxai (Zaishen quest)",
    1025: "Urgoz (Zaishen quest)",
    1026: "Chung, the Attuned (Zaishen quest)",
    1027: "Royen Beastkeeper (Zaishen quest)",
    1028: "Kunvie Firewing (Zaishen quest)",
    1029: "Mungri Magicbox (Zaishen quest)",
    1030: "Arbor Earthcall (Zaishen quest)",
    1031: "Mohby Windbeak (Zaishen quest)",
    1032: "Ssuns, Blessed of Dwayna (Zaishen quest)",
    1033: "Ghial the Bone Dancer (Zaishen quest)",
    1034: "Quansong Spiritspeak (Zaishen quest)",
    1035: "Baubao Wavewrath (Zaishen quest)",
    1036: "Jarimiya the Unmerciful (Zaishen quest)",
    1037: "Commander Wahli (Zaishen quest)",
    1038: "Droajam, Mage of the Sands (Zaishen quest)",
    1039: "Jedeh the Mighty (Zaishen quest)",
    1040: "Korshek the Immolated (Zaishen quest)",
    1041: "Admiral Kantoh (Zaishen quest)",
    1042: None,
    1043: "The Black Beast of Arrgh (Zaishen quest)",
    1044: "Lord Jadoth (Zaishen quest)",
    1045: "The Stygian Underlords (Zaishen quest)",
    1046: "The Stygian Lords (Zaishen quest)",
    1047: "The Greater Darkness (Zaishen quest)",
    1048: "Ilsundur, Lord of Fire (Zaishen quest)",
    1049: "Rragar Maneater (Zaishen quest)",
    1050: "Murakai, Lady of the Night (Zaishen quest)",
    1051: "Prismatic Ooze (Zaishen quest)",
    1052: "Havok Soulwail (Zaishen quest)",
    1053: "Frostmaw the Kinslayer (Zaishen quest)",
    1054: "Remnant of Antiquities (Zaishen quest)",
    1055: "Plague of Destruction (Zaishen quest)",
    1056: "Zoldark the Unholy (Zaishen quest)",
    1057: "Khabuus (Zaishen quest)",
    1058: "Z'him Monns (Zaishen quest)",
    1059: "Eldritch Ettin (Zaishen quest)",
    1060: "Fendi Nin (Zaishen quest)",
    1061: "TPS Regulator Golem (Zaishen quest)",
    1062: "Arachni (Zaishen quest)",
    1063: "Forgewight (Zaishen quest)",
    1064: "Selvetarm (Zaishen quest)",
    1065: "Justiciar Thommis (Zaishen quest)",
    1066: "Rand Stormweaver (Zaishen quest)",
    1067: "Duncan the Black (Zaishen quest)",
    1068: "Fronis Irontoe (Zaishen quest)",
    1069: None,
    1070: "Magmus (Zaishen quest)",
    1071: "Molotov Rocktail (Zaishen quest)",
    1072: "Nulfastu, Earthbound (Zaishen quest)",
    1073: None,
    1074: "Pywatt the Swift (Zaishen quest)",
    1075: "Joffs the Mitigator (Zaishen quest)",
    1076: "Mobrin, Lord of the Marsh (Zaishen quest)",
    1077: "Borrguus Blisterbark (Zaishen quest)",
    1078: "Fozzy Yeoryios (Zaishen quest)",
    1079: "Myish, Lady of the Lake (Zaishen quest)",
    1080: "Fenrir (Zaishen quest)",
    1081: "Vengeful Aatxe (Zaishen quest)",
    1082: "The Four Horsemen (Zaishen quest)",
    1083: "Charged Blackness (Zaishen quest)",
    1084: "Dragon Lich (Zaishen quest)",
    1085: "Priest of Menzies (Zaishen quest)",
    1086: "Lord Khobay (Zaishen quest)",
    1087: "Random Arena (Zaishen quest)",
    1088: None,
    1089: "Hero Battles (Zaishen quest)",
    1090: "Fort Aspenwood (Zaishen quest)",
    1091: "Jade Quarry (Zaishen quest)",
    1092: "Alliance Battles (Zaishen quest)",
    1093: "Guild Versus Guild (Zaishen quest)",
    1094: "Heroes' Ascent (Zaishen quest)",
    1095: "Random Arena (Zaishen quest)",
    1096: None,
    1097: "Hero Battles",
    1098: "Fort Aspenwood (Zaishen quest)",
    1099: "The Jade Quarry",
    1100: "Alliance Battles (Zaishen quest)",
    1101: "Guild Versus Guild (Zaishen quest)",
    1102: "Heroes' Ascent (Zaishen quest)",
    1103: "Random Arena (Zaishen quest)",
    1104: None,
    1105: None,
    1106: "Fort Aspenwood (Zaishen quest)",
    1107: "Jade Quarry (Zaishen quest)",
    1108: None,
    1109: "Guild Versus Guild (Zaishen quest)",
    1110: None,
    1111: "Random Arena (Zaishen quest)",
    1112: "Team Arena (Zaishen quest)",
    1113: "Hero Battles (Zaishen quest)",
    1114: None,
    1115: "Jade Quarry (Zaishen quest)",
    1116: "Alliance Battles (Zaishen quest)",
    1117: "Guild Versus Guild (Zaishen quest)",
    1118: "Heroes' Ascent (Zaishen quest)",
    1119: "Minister Cho's Estate (Zaishen quest)",
    1120: "Something Wicked This Way Comes",
    1121: "Don't Fear the Reapers",
    1122: "Stemming the Skeletal Tide",
    1123: "Every Bit Helps",
    1124: "The Waiting Game",
    1125: "Codex Arena (Zaishen quest)",
    1126: "Codex Arena (Zaishen quest)",
    1127: None,
    1128: "Codex Arena (Zaishen quest)",
    1129: "The Nightman Cometh",
    1130: "Wanted: Inquisitor Lashona",
    1131: "Wanted: Inquisitor Lovisa",
    1132: "Wanted: Inquisitor Bauer",
    1133: "Wanted: Justiciar Kasandra",
    1134: "Wanted: Justiciar Amilyn",
    1135: "Wanted: Justiciar Sevaan",
    1136: "Wanted: Valis the Rampant",
    1137: "Wanted: Maximilian the Meticulous",
    1138: "Wanted: Sarnia the Red-Handed",
    1139: "Wanted: Destor the Truth Seeker",
    1140: "Wanted: Selenas the Blunt",
    1141: "Wanted: Barthimus the Provident",
    1142: "Wanted: Cerris",
    1143: "Wanted: Carnak the Hungry",
    1144: "Wanted: Insatiable Vakar",
    1145: "Wanted: Amalek the Unmerciful",
    1146: "Wanted: Joh the Hostile",
    1147: "Wanted: Greves the Overbearing",
    1148: "Wanted: Calamitous",
    1149: "Wanted: Lev the Condemned",
    1150: "Wanted: Vess the Disputant",
    1151: "Wanted: Justiciar Kimii",
    1152: "Wanted: Zaln the Jaded",
    1153: "Wanted: Justiciar Marron",
    1154: "Riverside Assassination",
    1155: "A Little Help From Above",
    1156: "Temple of the Intolerable",
    1157: "Mustering a Response",
    1158: "The Battle for Lion's Arch",
    1159: "Heirlooms of the Mad King",
    1160: "Commandeering a Mortal Vessel",
    1161: "An Ingenious Plan",
    1162: "Til Death Do Us Part...",
    1163: "Open the Flood Gates of Death",
    1164: "The Killing Joke",
    1165: "Norn Catering",
    1166: "The Arrowhead",
    1167: "The Tarnished Emblem",
    1168: "The Broken Sword",
    1169: "The Mantle's Guise",
    1170: "Auspicious Beginnings",
    1171: "A Vengeance of Blades",
    1172: "Shadows in the Jungle",
    1173: "Rise",
    1174: "Reunion",
    1175: "The Wedding",
    1176: "The War in Kryta",
    1177: "Asuran Allies",
    1178: "Ebon Vanguard Allies",
    1179: "Operation: Crush Spirits",
    1180: "Fighting in a Winter Wonderland",
    1181: None,
    1182: "Vanguard Bounty: Blazefiend Griefblade",
    1183: None,
    1184: "Vanguard Bounty: Utini Wupwup",
    1185: None,
    1186: None,
    1187: "Vanguard Rescue: Save the Ascalonian Noble",
    1188: None,
    1189: "Vanguard Annihilation: Bandits",
    1190: "Vanguard Annihilation: Undead",
    1191: "Anvil Rock (Zaishen vanquish)",
    1192: "Arborstone (Zaishen vanquish)",
    1193: "Witman's Folly (Zaishen vanquish)",
    1194: "Arkjok Ward (Zaishen vanquish)",
    1195: "Ascalon Foothills (Zaishen vanquish)",
    1196: "Bahdok Caverns (Zaishen vanquish)",
    1197: "Cursed Lands (Zaishen vanquish)",
    1198: "Alcazia Tangle (Zaishen vanquish)",
    1199: "Archipelagos (Zaishen vanquish)",
    1200: "Eastern Frontier (Zaishen vanquish)",
    1201: "Dejarin Estate (Zaishen vanquish)",
    1202: "Watchtower Coast (Zaishen vanquish)",
    1203: "Arbor Bay (Zaishen vanquish)",
    1204: "Barbarous Shore (Zaishen vanquish)",
    1205: "Deldrimor Bowl (Zaishen vanquish)",
    1206: "Boreas Seabed (Zaishen vanquish)",
    1207: "Cliffs of Dohjok (Zaishen vanquish)",
    1208: "Diessa Lowlands (Zaishen vanquish)",
    1209: "Bukdek Byway (Zaishen vanquish)",
    1210: "Bjora Marches (Zaishen vanquish)",
    1211: "Crystal Overlook (Zaishen vanquish)",
    1212: "Diviner's Ascent (Zaishen vanquish)",
    1213: "Dalada Uplands (Zaishen vanquish)",
    1214: "Drazach Thicket (Zaishen vanquish)",
    1215: "Fahranur, the First City (Zaishen vanquish)",
    1216: "Dragon's Gullet (Zaishen vanquish)",
    1217: "Ferndale (Zaishen vanquish)",
    1218: "Forum Highlands (Zaishen vanquish)",
    1219: "Dreadnought's Drift (Zaishen vanquish)",
    1220: "Drakkar Lake (Zaishen vanquish)",
    1221: "Dry Top (Zaishen vanquish)",
    1222: "Tears of the Fallen (Zaishen vanquish)",
    1223: "Gyala Hatchery (Zaishen vanquish)",
    1224: "Ettin's Back (Zaishen vanquish)",
    1225: "Gandara, the Moon Fortress (Zaishen vanquish)",
    1226: "Grothmar Wardowns (Zaishen vanquish)",
    1227: "Flame Temple Corridor (Zaishen vanquish)",
    1228: "Haiju Lagoon (Zaishen vanquish)",
    1229: "Frozen Forest (Zaishen vanquish)",
    1230: "Garden of Seborhin (Zaishen vanquish)",
    1231: "Grenth's Footprint (Zaishen vanquish)",
    1232: "Jaya Bluffs (Zaishen vanquish)",
    1233: "Holdings of Chokhin (Zaishen vanquish)",
    1234: "Ice Cliff Chasms (Zaishen vanquish)",
    1235: "Griffon's Mouth (Zaishen vanquish)",
    1236: "Kinya Province (Zaishen vanquish)",
    1237: "Issnur Isles (Zaishen vanquish)",
    1238: "Jaga Moraine (Zaishen vanquish)",
    1239: "Ice Floe (Zaishen vanquish)",
    1240: "Maishang Hills (Zaishen vanquish)",
    1241: "Jahai Bluffs (Zaishen vanquish)",
    1242: "Riven Earth (Zaishen vanquish)",
    1243: "Icedome (Zaishen vanquish)",
    1244: "Minister Cho's Estate (Zaishen vanquish)",
    1245: "Mehtani Keys (Zaishen vanquish)",
    1246: "Sacnoth Valley (Zaishen vanquish)",
    1247: "Iron Horse Mine (Zaishen vanquish)",
    1248: "Morostav Trail (Zaishen vanquish)",
    1249: "Plains of Jarin (Zaishen vanquish)",
    1250: "Sparkfly Swamp (Zaishen vanquish)",
    1251: "Kessex Peak (Zaishen vanquish)",
    1252: "Mourning Veil Falls (Zaishen vanquish)",
    1253: "The Alkali Pan (Zaishen vanquish)",
    1254: "Varajar Fells (Zaishen vanquish)",
    1255: "Lornar's Pass (Zaishen vanquish)",
    1256: "Pongmei Valley (Zaishen vanquish)",
    1257: "The Floodplain of Mahnkelon (Zaishen vanquish)",
    1258: "Verdant Cascades (Zaishen vanquish)",
    1259: "Majesty's Rest (Zaishen vanquish)",
    1260: "Raisu Palace (Zaishen vanquish)",
    1261: "The Hidden City of Ahdashim (Zaishen vanquish)",
    1262: "Rhea's Crater (Zaishen vanquish)",
    1263: "Mamnoon Lagoon (Zaishen vanquish)",
    1264: "Shadow's Passage (Zaishen vanquish)",
    1265: "The Mirror of Lyss (Zaishen vanquish)",
    1266: "Saoshang Trail (Zaishen vanquish)",
    1267: "Nebo Terrace (Zaishen vanquish)",
    1268: "Shenzun Tunnels (Zaishen vanquish)",
    1269: "The Ruptured Heart (Zaishen vanquish)",
    1270: "Salt Flats (Zaishen vanquish)",
    1271: "North Kryta Province (Zaishen vanquish)",
    1272: "Silent Surf (Zaishen vanquish)",
    1273: "The Shattered Ravines (Zaishen vanquish)",
    1274: "Scoundrel's Rise (Zaishen vanquish)",
    1275: "Old Ascalon (Zaishen vanquish)",
    1276: "Sunjiang District (Zaishen vanquish)",
    1277: "The Sulfurous Wastes (Zaishen vanquish)",
    1278: "Magus Stones (Zaishen vanquish)",
    1279: "Perdition Rock (Zaishen vanquish)",
    1280: "Sunqua Vale (Zaishen vanquish)",
    1281: "Turai's Procession (Zaishen vanquish)",
    1282: "Norrhart Domains (Zaishen vanquish)",
    1283: "Pockmark Flats (Zaishen vanquish)",
    1284: "Tahnnakai Temple (Zaishen vanquish)",
    1285: "Vehjin Mines (Zaishen vanquish)",
    1286: "Poisoned Outcrops (Zaishen vanquish)",
    1287: "Prophet's Path (Zaishen vanquish)",
    1288: "The Eternal Grove (Zaishen vanquish)",
    1289: "Tasca's Demise (Zaishen vanquish)",
    1290: "Resplendent Makuun (Zaishen vanquish)",
    1291: "Reed Bog (Zaishen vanquish)",
    1292: "Unwaking Waters (Zaishen vanquish)",
    1293: "Stingray Strand (Zaishen vanquish)",
    1294: "Sunward Marches (Zaishen vanquish)",
    1295: "Regent Valley (Zaishen vanquish)",
    1296: "Wajjun Bazaar (Zaishen vanquish)",
    1297: "Yatendi Canyons (Zaishen vanquish)",
    1298: "Twin Serpent Lakes (Zaishen vanquish)",
    1299: "Sage Lands (Zaishen vanquish)",
    1300: "Xaquang Skyway (Zaishen vanquish)",
    1301: "Zehlon Reach (Zaishen vanquish)",
    1302: "Tangle Root (Zaishen vanquish)",
    1303: "Silverwood (Zaishen vanquish)",
    1304: "Zen Daijun (Zaishen vanquish)",
    1305: "The Arid Sea (Zaishen vanquish)",
    1306: "Nahpui Quarter (Zaishen vanquish)",
    1307: "Skyward Reach (Zaishen vanquish)",
    1308: "The Scar (Zaishen vanquish)",
    1309: "The Black Curtain (Zaishen vanquish)",
    1310: "Panjiang Peninsula (Zaishen vanquish)",
    1311: "Snake Dance (Zaishen vanquish)",
    1312: "Traveler's Vale (Zaishen vanquish)",
    1313: "The Breach (Zaishen vanquish)",
    1314: "Lahtenda Bog (Zaishen vanquish)",
    1315: "Spearhead Peak (Zaishen vanquish)",
    1316: "Mount Qinkai (Zaishen vanquish)",
    1317: "Marga Coast (Zaishen vanquish)",
    1318: "Melandru's Hope (Zaishen vanquish)",
    1319: "The Falls (Zaishen vanquish)",
    1320: "Joko's Domain (Zaishen vanquish)",
    1321: "Vulture Drifts (Zaishen vanquish)",
    1322: "Wilderness of Bahdza (Zaishen vanquish)",
    1323: "Talmark Wilderness (Zaishen vanquish)",
    1324: "Vehtendi Valley (Zaishen vanquish)",
    1325: "Talus Chute (Zaishen vanquish)",
    1326: "Mineral Springs (Zaishen vanquish)",
    1327: None,
    1328: None,
    1329: "The Path to Combat: Random Arena",
    1330: "The Path to Victory: Random Arenas",
    1331: "The Path to Combat: Codex Arena",
    1332: "The Path to Victory: Codex Arena",
    1333: "The Path to Combat: Guild Battles",
    1334: "The Path to Victory: Guild Battles",
    1335: "The Path to Combat: Heroes' Ascent",
    1336: "The Path to Victory: Heroes' Ascent (suspected)",
    1337: None,
    1338: None,
    1339: None,
    1340: None,
    1341: None,
    1342: "Cleansing Bukdek Byway",
    1343: "Cleansing Bukdek Byway (Hard mode)",
    1344: "Cleansing Shadow's Passage",
    1345: "Cleansing Shadow's Passage (Hard mode)",
    1346: "Cleansing Shenzun Tunnels",
    1347: "Cleansing Shenzun Tunnels (Hard mode)",
    1348: "Cleansing the Undercity",
    1349: "Cleansing the Undercity (Hard mode)",
    1350: "Cleansing the Sunjiang District",
    1351: "Cleansing the Sunjiang District (Hard mode)",
    1352: "Cleansing Pongmei Valley",
    1353: "Cleansing Pongmei Valley (Hard mode)",
    1354: "Rescue at Minister Cho's Estate",
    1355: "Rescue at Minister Cho's Estate (Hard mode)",
    1356: "Cleansing Haiju Lagoon",
    1357: "Cleansing Haiju Lagoon (Hard mode)",
    1358: "Cleansing Zen Daijun",
    1359: "Cleansing Zen Daijun (Hard mode)",
    1360: "Cleansing Rhea's Crater",
    1361: "Cleansing Rhea's Crater (Hard mode)",
    1362: "Cleansing the Silent Surf",
    1363: "Cleansing the Silent Surf (Hard mode)",
    1364: "Cleansing Morostav Trail",
    1365: "Cleansing Morostav Trail (Hard mode)",
    1366: "Intercepting the Am Fah",
    1367: "Intercepting the Am Fah (Hard mode)",
    1368: "Tracking the Corruption",
    1369: "Tracking the Corruption (Hard mode)",
    1370: "Architect of Corruption",
    1371: "Architect of Corruption (Hard mode)",
    1372: "The Gangs of Kaineng",
    1373: "The Gangs of Kaineng (Hard mode)",
    1374: "What Waits in Shadow",
    1375: "What Waits in Shadow (Hard mode)",
    1376: "A Chance Encounter",
    1377: "A Chance Encounter (Hard mode)",
    1378: "Cantha Courier Crisis",
    1379: "Cantha Courier Crisis (Hard mode)",
    1380: "Light My Fire",
    1381: "Light My Fire (Hard mode)",
    1382: "When Kappa Attack",
    1383: "When Kappa Attack (Hard mode)",
    1384: "A Favor Returned",
    1385: "Deadly Cargo",
    1386: "Trading Blows",
    1387: "Ever Closer to the Edge",
    1388: "Violence in the Streets",
    1389: "A Favor Returned (Hard mode)",
    1390: "Deadly Cargo (Hard mode)",
    1391: "Trading Blows (Hard mode)",
    1392: "Ever Closer to the Edge (Hard mode)",
    1393: "Violence in the Streets (Hard mode)",
    1394: "The Rescue Attempt",
    1395: "The Rescue Attempt (Hard mode)",
    1396: "Warning the Angchu",
    1397: "Free Birds",
    1398: "Honorable Combat",
    1399: "A Treaty's a Treaty",
    1400: "Warning the Angchu (Hard mode)",
    1401: "Free Birds (Hard mode)",
    1402: "Honorable Combat (Hard mode)",
    1403: "A Treaty's a Treaty (Hard mode)",
    1404: "Family Matters",
    1405: "Family Matters (Hard mode)",
    1406: "Evil Residents",
    1407: "Evil Residents Code: Harmonica",
    1408: "Finding Jinnai",
    1409: "Finding Jinnai (Hard mode)",
    1410: "Calling All Thugs",
    1411: "Raid on Kaineng Center",
    1412: "There Goes the Neighborhood",
    1413: "Ministry of Oppression",
    1414: "Calling All Thugs (Hard mode)",
    1415: "Raid on Kaineng Center (Hard mode)",
    1416: "There Goes the Neighborhood (Hard mode)",
    1417: "Ministry of Oppression (Hard mode)",
    1418: "Raid on Shing Jea Monastery",
    1419: "Raid on Shing Jea Monastery (Hard mode)",
    1420: "The Final Confrontation",
    1421: "The Final Confrontation (Hard mode)",
    1422: "Memories of Purity",
    1423: "Vassal States",
    1424: "Vassal States (Hard mode)",
    1425: "Redemption for the Lost",
    1426: "Redemption for the Lost (Hard mode)",
    1427: None,
    1428: None,
    1429: "Wayfarer's Reverie: Tyria",
    1430: "Wayfarer's Reverie: Cantha",
    1431: "Wayfarer's Reverie: Elona",
    1432: "Wayfarer's Reverie: The Far North",
    1433: "Mad Little Pony",
    1434: "Better You Than Me",
    1435: "Double Your Pleasure and RUN!",
    1436: "A Humbling Gift",
    1437: "The Polar Depressed",
    1438: "Take My Sister, Please",
    1439: "Pilgrimage to the Hall of Heroes"
}

# Build reverse lookup: Quest Name -> Quest ID(s)
# Some quests have duplicate names, so values are lists
QUEST_NAMES = {}
for qid, qname in QUEST_DATA.items():
    if qname is not None:
        if qname not in QUEST_NAMES:
            QUEST_NAMES[qname] = []
        QUEST_NAMES[qname].append(qid)


def get_quest_id(quest_name: str) -> int:
    """
    Get the quest ID for a given quest name.
    
    Args:
        quest_name: The name of the quest (case-insensitive)
    
    Returns:
        The quest ID, or None if not found
        
    Note: If multiple quests have the same name, returns the first ID.
    Use get_quest_ids() to get all matching IDs.
    
    Example:
        >>> get_quest_id("The Royal Papers")
        10
    """
    for name, ids in QUEST_NAMES.items():
        if name.lower() == quest_name.lower():
            return ids[0] if ids else None
    return None


def get_quest_ids(quest_name: str) -> list:
    """
    Get all quest IDs for a given quest name (handles duplicates).
    
    Args:
        quest_name: The name of the quest (case-insensitive)
    
    Returns:
        List of quest IDs matching the name, or empty list if not found
        
    Example:
        >>> get_quest_ids("War Preparations")
        [35, 217, 218, 219, 220, 221, 222, 642, 643, 644]
    """
    for name, ids in QUEST_NAMES.items():
        if name.lower() == quest_name.lower():
            return ids
    return []


def get_quest_name(quest_id: int) -> str:
    """
    Get the quest name for a given quest ID.
    
    Args:
        quest_id: The quest ID
    
    Returns:
        The quest name, or None if not found
        
    Example:
        >>> get_quest_name(10)
        'The Royal Papers'
    """
    return QUEST_DATA.get(quest_id)
