item_types = {
    0: 'ItemType_Salvage',
    1: 'ItemType_Leadhand',
    2: 'ItemType_Axe',
    3: 'ItemType_Bag',
    4: 'ItemType_Feet',
    5: 'ItemType_Bow',
    6: 'ItemType_Bundle',
    7: 'ItemType_Chest',
    8: 'ItemType_Rune',
    9: 'ItemType_Consumable',
    10: 'ItemType_Dye',
    11: 'ItemType_Material',
    12: 'ItemType_Focus',
    13: 'ItemType_Arms',
    14: 'ItemType_Sigil',
    15: 'ItemType_Hammer',
    16: 'ItemType_Head',
    17: 'ItemType_SalvageItem',
    18: 'ItemType_Key',
    19: 'ItemType_Legs',
    20: 'ItemType_Coins',
    21: 'ItemType_QuestItem',
    22: 'ItemType_Wand',
    24: 'ItemType_Shield',
    26: 'ItemType_Staff',
    27: 'ItemType_Sword',
    29: 'ItemType_Kit',
    30: 'ItemType_Trophy',
    31: 'ItemType_Scroll',
    32: 'ItemType_Daggers',
    33: 'ItemType_Present',
    34: 'ItemType_Minipet',
    35: 'ItemType_Scythe',
    36: 'ItemType_Spear',
    43: 'ItemType_Handbook',
    44: 'ItemType_CostumeBody',
    45: 'ItemType_CostumeHead',
}

dye_colors = {
    0: 'DyeColor_None',
    2: 'DyeColor_Blue',
    3: 'DyeColor_Green',
    4: 'DyeColor_Purple',
    5: 'DyeColor_Red',
    6: 'DyeColor_Yellow',
    7: 'DyeColor_Brown',
    8: 'DyeColor_Orange',
    9: 'DyeColor_Silver',
    10: 'DyeColor_Black',
    11: 'DyeColor_Gray',
    12: 'DyeColor_White',
    13: 'DyeColor_Pink',
}

professions = {
    0 : 'Profession_None',
    1 : 'Profession_Warrior',
    2 : 'Profession_Ranger',
    3 : 'Profession_Monk',
    4 : 'Profession_Necromancer',
    5 : 'Profession_Mesmer',
    6 : 'Profession_Elementalist',
    7 : 'Profession_Assassin',
    8 : 'Profession_Ritualist',
    9 : 'Profession_Paragon',
    10 : 'Profession_Dervish',
}

campaign_types = {
    0: 'CampaignType_Pvp',
    1: 'CampaignType_Prophecies',
    2: 'CampaignType_Faction',
    3: 'CampaignType_Nightfall',
}

bag_types = {
    1: 'BagType_Bag',
    2: 'BagType_Equipped',
    3: 'BagType_NotCollected',
    4: 'BagType_Storage',
    5: 'BagType_MatStorage',
}

bag_model_ids = {
    0: 'BagModelId_Backpack',
    1: 'BagModelId_BeltPouch',
    2: 'BagModelId_Bag1',
    3: 'BagModelId_Bag2',
    4: 'BagModelId_EquipmentPack',
    5: 'BagModelId_MaterialStorage',
    6: 'BagModelId_UnclaimedItems',
    7: 'BagModelId_Storage1',
    8: 'BagModelId_Storage2',
    9: 'BagModelId_Storage3',
    10: 'BagModelId_Storage4',
    11: 'BagModelId_Storage5',
    12: 'BagModelId_Storage6',
    13: 'BagModelId_Storage7',
    14: 'BagModelId_Storage8',
    15: 'BagModelId_Storage9',
    16: 'BagModelId_Storage10',
    17: 'BagModelId_Storage11',
    18: 'BagModelId_Storage12',
    19: 'BagModelId_Storage13',
    20: 'BagModelId_StorageAnniversary',
    21: 'BagModelId_EquippedItems',
}

titles = {
    0: 'Hero',
    1: 'TyrianCarto',
    2: 'CanthanCarto',
    3: 'Gladiator',
    4: 'Champion',
    5: 'Kurzick',
    6: 'Luxon',
    7: 'Drunkard',
    8: 'Deprecated_SkillHunter',
    9: 'Survivor',
    10: 'KoaBD',
    11: 'Deprecated_TreasureHunter',
    12: 'Deprecated_Wisdom',
    13: 'ProtectorTyria',
    14: 'ProtectorCantha',
    15: 'Lucky',
    16: 'Unlucky',
    17: 'Sunspear',
    18: 'ElonianCarto',
    19: 'ProtectorElona',
    20: 'Lightbringer',
    21: 'LDoA',
    22: 'Commander',
    23: 'Gamer',
    24: 'SkillHunterTyria',
    25: 'VanquisherTyria',
    26: 'SkillHunterCantha',
    27: 'VanquisherCantha',
    28: 'SkillHunterElona',
    29: 'VanquisherElona',
    30: 'LegendaryCarto',
    31: 'LegendaryGuardian',
    32: 'LegendarySkillHunter',
    33: 'LegendaryVanquisher',
    34: 'Sweets',
    35: 'GuardianTyria',
    36: 'GuardianCantha',
    37: 'GuardianElona',
    38: 'Asuran',
    39: 'Deldrimor',
    40: 'Vanguard',
    41: 'Norn',
    42: 'MasterOfTheNorth',
    43: 'Party',
    44: 'Zaishen',
    45: 'TreasureHunter',
    46: 'Wisdom',
    47: 'Codex',
}
