default_schema_version = "1.0"

global_widget_defaults = {
    "WidgetManager": {"old_menu": "False", "enable_all": "True"},
    "QuickDock": {
        "enable_quick_dock": "True",
        "width": "10",
        "height": "50",
        "offset_y": "545",
        "edge": "left",
        "unlocked": "False",
        "buttons_per_row": "8",
    },
    "QuickDockColor": {
        "r": "0.6000000238418579",
        "g": "0.800000011920929",
        "b": "1.0",
        "a": "1.0",
    },
    "FloatingMenu": {
        "floating_attachment_index": "3",
        "fmx": "100",
        "fmy": "100",
        "floating_drag_locked": "True",
        "use_custom_colors": "False",
        "base_r": "0.1",
        "base_g": "0.1",
        "base_b": "0.1",
        "base_a": "1.0",
        "hover_r": "0.15",
        "hover_g": "0.15",
        "hover_b": "0.15",
        "hover_a": "1.0",
        "active_r": "0.05",
        "active_g": "0.05",
        "active_b": "0.05",
        "active_a": "1.0",
        "border_r": "0.3",
        "border_g": "0.3",
        "border_b": "0.3",
        "border_a": "1.0",
    },
    "HeroAI": {
        "enabled": "True",
        "category": "Bots",
        "subcategory": "Multiboxing",
        "icon": "ICON_RUNNING",
        "quickdock": "True",
    },
    "HeroHelper": {
        "enabled": "False",
        "category": "Bots",
        "subcategory": "Helpers",
        "icon": "ICON_PEOPLE_CARRY",
        "quickdock": "True",
    },
    "Pet Helper": {
        "enabled": "True",
        "category": "Bots",
        "subcategory": "Helpers",
        "icon": "ICON_DOG",
        "quickdock": "True",
    },
    "Action Queue Monitor": {
        "enabled": "False",
        "category": "Coding",
        "subcategory": "Info",
        "icon": "ICON_INFO_CIRCLE",
        "quickdock": "True",
    },
    "Agent Info": {
        "enabled": "False",
        "category": "Coding",
        "subcategory": "Info",
        "icon": "ICON_BOOK",
        "quickdock": "True",
    },
    "Icon Explorer": {
        "enabled": "False",
        "category": "Coding",
        "subcategory": "ImGui",
        "icon": "ICON_EXPAND",
        "quickdock": "True",
    },
    "Py4GW_DEMO": {
        "enabled": "False",
        "category": "Coding",
        "subcategory": "Info",
        "icon": "ICON_INFO",
        "quickdock": "True",
    },
    "Environment Upkeeper": {
        "enabled": "True",
        "category": "Coding",
        "subcategory": "Environment",
        "icon": "ICON_TREE",
        "quickdock": "False",
    },
    "Compass +": {
        "enabled": "False",
        "category": "Gameplay",
        "subcategory": "Overlays",
        "icon": "ICON_COMPASS",
        "quickdock": "True",
    },
    "Drop Unyielding Aura": {
        "enabled": "False",
        "category": "Gameplay",
        "subcategory": "Triggers",
        "icon": "ICON_EYE_DROPPER",
        "quickdock": "True",
    },
    "Enter character on load": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Triggers",
        "icon": "ICON_PLAY_CIRCLE",
        "quickdock": "True",
    },
    "Instance Timer": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Overlays",
        "icon": "ICON_CLOCK",
        "quickdock": "True",
    },
    "Get Blessed": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Utilities",
        "icon": "ICON_HANDS",
        "quickdock": "True",
    },
    "Dialog Sync": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Utilities",
        "icon": "ICON_EXCLAMATION_CIRCLE",
        "quickdock": "True",
    },
    "Inventory +": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Utilities",
        "icon": "ICON_SHOPPING_BAG",
        "quickdock": "True",
    },
    "LootManager": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Utilities",
        "icon": "ICON_SHOPPING_CART",
        "quickdock": "True",
    },
    "Mission Map +": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Overlays",
        "icon": "ICON_MAP",
        "quickdock": "True",
    },
    "PCons": {
        "enabled": "False",
        "category": "Gameplay",
        "subcategory": "Triggers",
        "icon": "ICON_CHEVRON_UP",
        "quickdock": "True",
    },
    "Switch Character": {
        "enabled": "False",
        "category": "Gameplay",
        "subcategory": "Utilities",
        "icon": "ICON_PEOPLE_ARROWS",
        "quickdock": "True",
    },
    "Resign on enter Map": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Triggers",
        "icon": "ICON_SKULL",
        "quickdock": "True",
    },
    "Return to outpost on defeat": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Triggers",
        "icon": "ICON_HOME",
        "quickdock": "True",
    },
    "Skip Cinematics": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Triggers",
        "icon": "ICON_FAST_FORWARD",
        "quickdock": "True",
    },
    "Titles": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Triggers",
        "icon": "ICON_ID_BADGE",
        "quickdock": "True",
    },
    "Travel": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Utilities",
        "icon": "ICON_PLANE",
        "quickdock": "True",
    },
    "Vanquish": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Overlays",
        "icon": "ICON_FLAG_CHECKERED",
        "quickdock": "True",
    },
    "Survival Title Helper": {
        "enabled": "False",
        "category": "Bots",
        "subcategory": "Helpers",
        "icon": "ICON_FLAG_CHECKERED",
        "quickdock": "True",
    },
    "CombatPrep": {
        "enabled": "False",
        "category": "Bots",
        "subcategory": "Helpers",
        "icon": "ICON_BRAIN",
        "quickdock": "True",
    },
    "CustomBehaviors": {
        "enabled": "False",
        "category": "Bots",
        "subcategory": "Helpers",
        "icon": "ICON_PEOPLE_CARRY",
        "quickdock": "True"
    },
    "NFDialogSender": {
        "enabled": "False",
        "category": "Gameplay",
        "subcategory": "Utilities",
        "icon": "ICON_PEOPLE_CARRY",
        "quickdock": "True",
    },
    "CanthaDialogSender": {
        "enabled": "False",
        "category": "Gameplay",
        "subcategory": "Utilities",
        "icon": "ICON_PEOPLE_CARRY",
        "quickdock": "True",
    },
    "TeamInventoryViewer": {
        "enabled": "False",
        "category": "Gameplay",
        "subcategory": "Utilities",
        "icon": "ICON_BRAIN",
        "quickdock": "True",
    },
    "CombatEventsTester": {
        "enabled": "False",
        "category": "Coding",
        "subcategory": "Info",
        "icon": "ICON_CROSSHAIRS",
        "quickdock": "True",
    },
    # TODO: Register your Widget here
}

account_widget_defaults = {
    "WidgetManager": {
        "old_menu": "False",
        "enable_all": "True",
        "use_account_settings": "False",
    },
    "QuickDock": {
        "enable_quick_dock": "True",
        "width": "10",
        "height": "50",
        "offset_y": "545",
        "edge": "left",
        "unlocked": "False",
        "buttons_per_row": "8",
    },
    "QuickDockColor": {
        "r": "0.6000000238418579",
        "g": "0.800000011920929",
        "b": "1.0",
        "a": "1.0",
    },
    "FloatingMenu": {
        "floating_attachment_index": "3",
        "fmx": "100",
        "fmy": "100",
        "floating_drag_locked": "True",
        "use_custom_colors": "False",
        "base_r": "0.1",
        "base_g": "0.1",
        "base_b": "0.1",
        "base_a": "1.0",
        "hover_r": "0.15",
        "hover_g": "0.15",
        "hover_b": "0.15",
        "hover_a": "1.0",
        "active_r": "0.05",
        "active_g": "0.05",
        "active_b": "0.05",
        "active_a": "1.0",
        "border_r": "0.3",
        "border_g": "0.3",
        "border_b": "0.3",
        "border_a": "1.0",
    },
    "HeroAI": {
        "enabled": "True",
        "category": "Bots",
        "subcategory": "Multiboxing",
        "icon": "ICON_RUNNING",
        "quickdock": "True",
    },
    "HeroHelper": {
        "enabled": "False",
        "category": "Bots",
        "subcategory": "Helpers",
        "icon": "ICON_PEOPLE_CARRY",
        "quickdock": "True",
    },
    "Pet Helper": {
        "enabled": "True",
        "category": "Bots",
        "subcategory": "Helpers",
        "icon": "ICON_DOG",
        "quickdock": "True",
    },
    "Action Queue Monitor": {
        "enabled": "False",
        "category": "Coding",
        "subcategory": "Info",
        "icon": "ICON_INFO_CIRCLE",
        "quickdock": "True",
    },
    "Agent Info": {
        "enabled": "False",
        "category": "Coding",
        "subcategory": "Info",
        "icon": "ICON_BOOK",
        "quickdock": "True",
    },
    "Icon Explorer": {
        "enabled": "False",
        "category": "Coding",
        "subcategory": "ImGui",
        "icon": "ICON_EXPAND",
        "quickdock": "True",
    },
    "Py4GW_DEMO": {
        "enabled": "False",
        "category": "Coding",
        "subcategory": "Info",
        "icon": "ICON_INFO",
        "quickdock": "True",
    },
    "Environment Upkeeper": {
        "enabled": "True",
        "category": "Coding",
        "subcategory": "Environment",
        "icon": "ICON_TREE",
        "quickdock": "False",
    },
    "Compass +": {
        "enabled": "False",
        "category": "Gameplay",
        "subcategory": "Overlays",
        "icon": "ICON_COMPASS",
        "quickdock": "True",
    },
    "Drop Unyielding Aura": {
        "enabled": "False",
        "category": "Gameplay",
        "subcategory": "Triggers",
        "icon": "ICON_EYE_DROPPER",
        "quickdock": "True",
    },
    "Enter character on load": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Triggers",
        "icon": "ICON_PLAY_CIRCLE",
        "quickdock": "True",
    },
    "Instance Timer": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Overlays",
        "icon": "ICON_CLOCK",
        "quickdock": "True",
    },
    "Get Blessed": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Utilities",
        "icon": "ICON_HANDS",
        "quickdock": "True",
    },
    "Dialog Sync": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Utilities",
        "icon": "ICON_EXCLAMATION_CIRCLE",
        "quickdock": "True",
    },
    "Inventory +": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Utilities",
        "icon": "ICON_SHOPPING_BAG",
        "quickdock": "True",
    },
    "LootManager": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Utilities",
        "icon": "ICON_SHOPPING_CART",
        "quickdock": "True",
    },
    "Mission Map +": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Overlays",
        "icon": "ICON_MAP",
        "quickdock": "True",
    },
    "PCons": {
        "enabled": "False",
        "category": "Gameplay",
        "subcategory": "Triggers",
        "icon": "ICON_CHEVRON_UP",
        "quickdock": "True",
    },
    "Switch Character": {
        "enabled": "False",
        "category": "Gameplay",
        "subcategory": "Utilities",
        "icon": "ICON_PEOPLE_ARROWS",
        "quickdock": "True",
    },
    "Resign on enter Map": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Triggers",
        "icon": "ICON_SKULL",
        "quickdock": "True",
    },
    "Return to outpost on defeat": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Triggers",
        "icon": "ICON_HOME",
        "quickdock": "True",
    },
    "Skip Cinematics": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Triggers",
        "icon": "ICON_FAST_FORWARD",
        "quickdock": "True",
    },
    "Titles": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Triggers",
        "icon": "ICON_ID_BADGE",
        "quickdock": "True",
    },
    "Travel": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Utilities",
        "icon": "ICON_PLANE",
        "quickdock": "True",
    },
    "Vanquish": {
        "enabled": "True",
        "category": "Gameplay",
        "subcategory": "Overlays",
        "icon": "ICON_FLAG_CHECKERED",
        "quickdock": "True",
    },
    "Survival Title Helper": {
        "enabled": "False",
        "category": "Bots",
        "subcategory": "Helpers",
        "icon": "ICON_FLAG_CHECKERED",
        "quickdock": "True",
    },
    "CombatPrep": {
        "enabled": "False",
        "category": "Bots",
        "subcategory": "Helpers",
        "icon": "ICON_BRAIN",
        "quickdock": "True",
    },
    "CustomBehaviors": {
        "enabled": "False",
        "category": "Bots",
        "subcategory": "Helpers",
        "icon": "ICON_PEOPLE_CARRY",
        "quickdock": "True"
    },
    "NFDialogSender": {
        "enabled": "False",
        "category": "Gameplay",
        "subcategory": "Utilities",
        "icon": "ICON_PEOPLE_CARRY",
        "quickdock": "True",
    },
    "CanthaDialogSender": {
        "enabled": "False",
        "category": "Gameplay",
        "subcategory": "Utilities",
        "icon": "ICON_PEOPLE_CARRY",
        "quickdock": "True",
    },
    "EZ Cast": {
        "enabled": "False",
        "category": "Bots",
        "subcategory": "Helpers",
        "icon": "ICON_BRAIN",
        "quickdock": "True",
    },
    "Central Commander": {
        "enabled": "False",
        "category": "Bots",
        "subcategory": "Multiboxing",
        "icon": "ICON_BRAIN",
        "quickdock": "True",
    },
    "TeamInventoryViewer": {
        "enabled": "False",
        "category": "Gameplay",
        "subcategory": "Utilities",
        "icon": "ICON_BRAIN",
        "quickdock": "True",
    },
    "CombatEventsTester": {
        "enabled": "False",
        "category": "Coding",
        "subcategory": "Info",
        "icon": "ICON_CROSSHAIRS",
        "quickdock": "True",
    },
    # TODO: Register your Widget here
}
