from typing import List
import PyOverlay 



class Py2DRenderer:
    def __init__(self) -> None: ...

    def set_primitives(self, shapes: List[List[PyOverlay.Point2D]], color: int) -> None: ...
    def build_pathing_trapezoid_geometry(self, color: int) -> None: ...
    def set_world_zoom_x(self, zoom: float) -> None: ...
    def set_world_zoom_y(self, zoom: float) -> None: ...
    def set_world_pan(self, x:float, y:float) -> None: ...
    def set_world_rotation(self, rotation: float) -> None: ...
    def set_world_space(self, enabled: bool) -> None: ...
    def set_world_scale(self, scale: float) -> None: ...
    
    def set_screen_offset(self, x: float, y: float) -> None: ...
    def set_screen_zoom_x(self, zoom: float) -> None: ...
    def set_screen_zoom_y(self, zoom: float) -> None: ...
    def set_screen_rotation(self, rotation: float) -> None: ...

    def set_circular_mask(self, enabled: bool) -> None: ...
    def set_mask_radius(self, radius: float) -> None: ...
    def set_mask_center(self, x: float, y: float) -> None: ...
    
    def set_rectangle_mask(self, enabled: bool) -> None: ...
    def set_rectangle_mask_bounds(self, x: float, y: float, width: float, height: float) -> None: ...

    def render(self) -> None: ...

    def Setup3DView(self) -> None: ...
    def DrawLine(self,_from: PyOverlay.Point2D , _to: PyOverlay.Point2D, color:int, thickness:float) -> None: ...
    def DrawTriangle(self, p1: PyOverlay.Point2D, p2: PyOverlay.Point2D, p3: PyOverlay.Point2D, color:int, thickness:float) -> None: ...
    def DrawTriangleFilled(self, p1: PyOverlay.Point2D, p2: PyOverlay.Point2D, p3: PyOverlay.Point2D, color:int) -> None: ...
    def DrawQuad(self, p1: PyOverlay.Point2D, p2: PyOverlay.Point2D, p3: PyOverlay.Point2D, p4: PyOverlay.Point2D, color:int, thickness:float) -> None: ...
    def DrawQuadFilled(self, p1: PyOverlay.Point2D, p2: PyOverlay.Point2D, p3: PyOverlay.Point2D, p4: PyOverlay.Point2D, color:int) -> None: ...
    def DrawPoly(self, center: PyOverlay.Point2D, radius:float , color:int, segments:int, thickness:float) -> None: ...
    def DrawPolyFilled(self, center: PyOverlay.Point2D, radius:float , color:int, segments:int) -> None: ...

    def DrawLine3D(self, _from: PyOverlay.Point3D, _to: PyOverlay.Point3D, color:int, use_occlusion:bool, snap_to_ground_segments:int, floor_offset:float) -> None: ...
    def DrawTriangle3D(self, p1: PyOverlay.Point3D, p2: PyOverlay.Point3D, p3: PyOverlay.Point3D, color:int, use_occlusion:bool, snap_to_ground_segments:int, floor_offset:float) -> None: ...
    def DrawTriangleFilled3D(self, p1: PyOverlay.Point3D, p2: PyOverlay.Point3D, p3: PyOverlay.Point3D, color:int, use_occlusion:bool, snap_to_ground_segments:int, floor_offset:float) -> None: ...
    def DrawQuad3D(self, p1: PyOverlay.Point3D, p2: PyOverlay.Point3D, p3: PyOverlay.Point3D, p4: PyOverlay.Point3D, color:int, use_occlusion:bool, snap_to_ground_segments:int, floor_offset:float) -> None: ...
    def DrawQuadFilled3D(self, p1: PyOverlay.Point3D, p2: PyOverlay.Point3D, p3: PyOverlay.Point3D, p4: PyOverlay.Point3D, color:int, use_occlusion:bool, snap_to_ground_segments:int, floor_offset:float) -> None: ...
    def DrawPoly3D(self, center: PyOverlay.Point3D, radius:float , color:int, segments:int, use_occlusion:bool, snap_to_ground_segments:int, floor_offset:float) -> None: ...
    def DrawPolyFilled3D(self, center: PyOverlay.Point3D, radius:float , color:int, segments:int, use_occlusion:bool, snap_to_ground_segments:int, floor_offset:float) -> None: ...
    def DrawCubeOutline(self, center: PyOverlay.Point3D, size:float , color:int, use_occlusion:bool) -> None: ...
    def DrawCubeFilled(self, center: PyOverlay.Point3D, size:float , color:int, use_occlusion:bool) -> None: ...
    def ApplyStencilMask(self) -> None: ...
    def ResetStencilMask(self) -> None: ...
    def DrawTexture(self, file_path: str, screen_pos_x: float, screen_pos_y: float, width: float, height: float, tint: int) -> None: ...
    def DrawTexture3D(self, file_path: str, world_pos_x: float, world_pos_y: float, world_pos_z: float, width: float, height: float, use_occlusion: bool, tint: int) -> None: ...
    def DrawQuadTextured3D(self, file_path: str, p1: PyOverlay.Point3D, p2: PyOverlay.Point3D, p3: PyOverlay.Point3D, p4: PyOverlay.Point3D, use_occlusion: bool, tint: int) -> None: ...
    def SaveGeometryToFile(self, filename: str, min_x: float, min_y: float, max_x: float, max_y: float) -> int: ...