# PyDialogCatalog.pyi - Stub file for the PyDialogCatalog module

from typing import Any, List


class PyDialogCatalog:
    def __init__(self) -> None: ...

    @staticmethod
    def is_dialog_available(dialog_id: int) -> bool: ...
    @staticmethod
    def get_dialog_info(dialog_id: int) -> dict[str, Any]: ...
    @staticmethod
    def enumerate_available_dialogs() -> List[dict[str, Any]]: ...
    @staticmethod
    def get_dialog_text_decoded(dialog_id: int) -> str: ...
    @staticmethod
    def is_dialog_text_decode_pending(dialog_id: int) -> bool: ...
    @staticmethod
    def get_dialog_text_decode_status() -> List[dict[str, Any]]: ...
    @staticmethod
    def clear_cache() -> None: ...
