from typing import List


class PacketDirection:
    StoC: 'PacketDirection'
    CToS: 'PacketDirection'


class PacketLogEntry:
    tick: int
    direction: PacketDirection
    header: int
    size: int
    data: List[int]

    def __init__(self) -> None: ...


class PacketSniffer:
    def __init__(self) -> None: ...

    @staticmethod
    def instance() -> 'PacketSniffer': ...

    def initialize(self) -> bool: ...
    def initialize_stoc(self) -> bool: ...
    def initialize_ctos(self) -> bool: ...
    def terminate(self) -> None: ...
    def terminate_stoc(self) -> None: ...
    def terminate_ctos(self) -> None: ...
    def get_logs(self) -> List[PacketLogEntry]: ...
    def get_stoc_logs(self) -> List[PacketLogEntry]: ...
    def get_ctos_logs(self) -> List[PacketLogEntry]: ...
    def clear_logs(self) -> None: ...
    def clear_stoc_logs(self) -> None: ...
    def clear_ctos_logs(self) -> None: ...
