from typing import Optional, Iterator, TypeVar, Generic
from ctypes import Structure

class GW_BaseArray(Structure):
    m_buffer: int
    m_capacity: int
    m_size: int

class GW_Array(Structure):
    m_buffer: int
    m_capacity: int
    m_size: int
    m_param: int


T = TypeVar("T")

class GW_Array_View(Generic[T]):
    def __init__(self, arr: GW_Array, elem_type: type[T]) -> None: ...

    def valid(self) -> bool: ...
    def size(self) -> int: ...
    def capacity(self) -> int: ...

    def get(self, index: int) -> Optional[T]: ...

    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> T: ...
    def __iter__(self) -> Iterator[T]: ...
    def __reversed__(self) -> Iterator[T]: ...
    def to_list(self) -> list[T]: ...
    
class GW_Array_Value_View(Generic[T]):
    def __init__(self, arr: GW_Array, elem_type: type[T]) -> None: ...

    def valid(self) -> bool: ...
    def size(self) -> int: ...
    def capacity(self) -> int: ...

    def get(self, index: int) -> Optional[T]: ...

    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> T: ...
    def __iter__(self) -> Iterator[T]: ...
    def __reversed__(self) -> Iterator[T]: ...
    def to_list(self) -> list[T]: ...